# Время задержки отправки текстурпака после захода в тиках (20 тик = 1 секунда).
delay: 20

# Версия 1.7.x
'1.7.x': "url : hash"

# Версия 1.8.x
'1.8.x': "url : hash"

# Версия 1.9.x
'1.9.x': "url : hash"

# Версия 1.10.x
'1.10.x': "url : hash"

# Версия 1.11.x
'1.11.x': "url : hash"

# Версия 1.12.x
'1.12.x': "url : hash"

# Версия 1.13.x
'1.13.x': "url : hash"

# Версия 1.14.x
'1.14.x': "url : hash"

# Версия 1.15.x
'1.15.x': "url : hash"

# Версия 1.17.x
'1.17.x': "url : hash"

# Версия 1.18.x
'1.18.x': "url : hash"

# Версия 1.19.x
'1.19.x': "url : hash"

# Версия 1.20.x
'1.20.x': "url : hash"

# Остальные версии или все версии
'0x': "url : hash"